services:
  python:
    image: python:latest
    ports:
      - 80:80
    tty: true
    stdin_open: true
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    command: bash
