services:
  server:
    image: python:3
    ports:
      - 80:80
    tty: true
    stdin_open: true
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    command: bash -c "
        pip install --upgrade pip &&
        pip install -r requirements.txt &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:80
      "
